default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password #これは、docker-compose.ymlで指定したパスワード
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: menuvid_development

test:
  <<: *default
  database: menuvid_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
