default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password #これは、docker-compose.ymlで指定したパスワード
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: menu_vid_development

test:
  <<: *default
  database: menu_vid_test

production:
  <<: *default
  database: menu_vid_production
  # username: menu_vid
  # password: <%= ENV["MENUVID_DATABASE_PASSWORD"] %>
  # url: <%= ENV['DATABASE_URL'] %>
